/*
standard public schema

Testing IntrospectionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fugledata

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/yitech/fugledata-go"
)

func Test_fugledata_IntrospectionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IntrospectionAPIService RootGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.IntrospectionAPI.RootGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
